		.ORIG	X3000
		LD	R5, DECIMAL	; LOAD DECIMAL OFFSET
		LEA	R0, PROMPT	; LOAD PROMPT MESSAGE
		TRAP	X22		; PUT STRING
		TRAP	X20		; GET CHAR
		TRAP 	X21		; ECHO CHAR
;;;;	A-PART
		JSR	APART		; 	
		ADD	R2, R1, #0	; SAVES A-PART RESULT IN R2
;;;;	B-PART
		JSR	BPART		;
		ADD	R3, R1, #0	; SAVES B-PART RESULT IN R3
;;;;	C-PART
		ADD	R1, R0, R5	; TAKE CONVERTED INPUT AND PUT INTO R1
		JSR	CPART		;	C PART #1
		JSR	CPART		;	C PART #2
		ADD	R4, R1, #0	; SAVES C-PART RESULT IN R4
;;;;
	END	HALT			; END PROGRAM
	DECIMAL	.FILL	XFFD0
;;;;		
;   >>>>    A-PART	>>>		
;;;;		
	APART	ST	R7, SAVER7	; SAVE RETURN REGISTER
		ST	R4, SAVER4
		ST	R3, SAVER3	
		ST	R2, SAVER2
		LD	R4, BNUM	; LOAD THE B VALUE INTO R4
		LD	R3, ANUM	; LOAD THE A VALUE INTO R3
		ADD	R1, R0, R5	; TAKE INPUT, CONVERT, AND PUT INTO R1
		AND	R2, R2, #0	; CLEAR R2
	ALOOP	ADD	R2, R2, R1	; ADD R1 TO R1 AND STORE IN R2
		ADD	R3, R3, #-1	; R3--
		BRP	ALOOP
		ADD	R1, R2, R4
		LD	R7, SAVER7
		LD	R4, SAVER4
		LD	R3, SAVER3
		LD	R2, SAVER2
		RET	
	ANUM	.FILL	X0003
	BNUM	.FILL	X0004
;;;;	
;   >>>>    B-PART	>>>>		
;;;;	
	BPART	ST	R7, SAVER7	; SAVE RETURN REGISTER
		ST	R4, SAVER4
		ST	R3, SAVER3	
		ST	R2, SAVER2
		LD	R4, DNUM	; LOAD THE C VALUE INTO R4
		LD	R3, CNUM	; LOAD THE D VALUE INTO R3
		ADD	R1, R0, R5	; TAKE INPUT, CONVERT, AND PUT INTO R1
		AND	R2, R2, #0	; CLEAR R2
		BLOOP	ADD	R2, R2, R1	; ADD R1 TO R1 AND STORE IN R2
		ADD	R3, R3, #-1	; R3--
		BRP	BLOOP
		ADD	R1, R2, R4
		LD	R7, SAVER7
		LD	R4, SAVER4
		LD	R3, SAVER3
		LD	R2, SAVER2
		RET
	CNUM	.FILL	X0009	; #9
	DNUM	.FILL	X0010	; #16
;;;;	
;   >>>>    C-PART	>>>>		
;;;;		
	CPART	ST	R7, SAVER7	; SAVE RETURN REGISTER
		ST	R4, SAVER4
		ST	R3, SAVER3	
		ST	R2, SAVER2
		LD	R4, BNUM	; LOAD THE B VALUE INTO R4
		LD	R3, ANUM	; LOAD THE A VALUE INTO R3
		AND	R2, R2, #0	; CLEAR R2
	CLOOP	ADD	R2, R2, R1	; ADD R1 TO R1 AND STORE IN R2
		ADD	R3, R3, #-1	; R3--
		BRP	CLOOP
		ADD	R1, R2, R4
		LD	R7, SAVER7
		LD	R4, SAVER4
		LD	R3, SAVER3
		LD	R2, SAVER2
		RET
	SAVER7	.FILL	X0000
	SAVER4	.FILL	X0000	; SAVE LOCATION FOR C-PART
	SAVER3	.FILL	X0000	; SAVE LOCATION FOR B-PART
	SAVER2	.FILL	X0000	; SAVE LOCATION FOR A-PART
	PROMPT	.STRINGZ "PLEASE ENTER A NUMBER:> "
		.END